### ISSUE TITLE
Query Parameter "is_running" is not working for time entries

### ISSUE THREAD

**Issue by ahawlitschek** [jolicode/harvest-php-api#17] opened 2020-07-14 15:26 UTC
When trying to request only the running timer entries, every entry will be returned

```php
$entries = $harvestClient->listTimeEntries(['is_running' => true]);
dd($entries);
```

results in 

![image](https://user-images.githubusercontent.com/53199186/87444413-0afa6f00-c5f7-11ea-9e55-3a986228775f.png)

Somehow the filter is not applied. 
Obviously there aren't 100 timers running :D

**Comment by xavierlacot** [comment] 2020-07-27 09:32
The issue is related to the way the Harvest API expects to receive booleans (as the strings `true` or `false`). At the moment, we send boolean filters as `0` or `1` values, which doesn't work. So, all the boolean filters in this client are broken at the moment. Once merged, the pull request https://github.com/janephp/janephp/pull/358 in janephp will allow to fix this issue.

**Comment by ahawlitschek** [comment] 2020-07-27 09:41
Thanks for the reply!

So the issue will be gone in the near future. 
Thanks :)

**Closed** 2020-07-29 22:32 UTC
